### ISSUE TITLE
Unable to build Click with odin_agent/src files

### ISSUE THREAD

**Issue by uhlik1889** [lalithsuresh/odin-agent#3]
I am having trouble building the odin agent in Click. I copied all the src/ files, but the "sudo make" command stops at error, referencing some "undefined reference to..." in odinagent.cc.

Here is complete terminal output:
https://pastebin.com/R17WjRUX

Any help would be appreciated, because I have no idea how to solve this. Tried updating gcc compiler to 6.5 version, and still no change.

**Comment by lalithsuresh** [comment]
When you built Click, did you make sure to enable WiFi modules?

**Comment by uhlik1889** [comment]
I want to use it internally inside Linux only. Currently no external connections were considered. 
I am trying to link this to the Mininet-Wifi, in order to improve this simulation software. So I would need to create maybe some additional elements.

**Comment by lalithsuresh** [comment]
For the Odin Agent to compile, it needs to use methods available in Click's WiFi elements.  To do so, when building click, you need to use the "--enable-wifi" flag when invoking "./configure".

**Comment by uhlik1889** [comment]
Thanks for quick response, now there are not errors at the end, and the compile run smoothly. This is the end of "make" command.

https://pastebin.com/4pHsmMfg

**Comment by lalithsuresh** [comment]
Great to hear!
