### ISSUE TITLE
Generated agent.click file but with error message

### ISSUE THREAD

**Issue by uhlik1889** [lalithsuresh/odin-agent#4]
Hi I compiled the Click as you stated, and wanted to use that script to generate 
agent.click, but some error message appeared. The agent.click file got generated either way,
so I just wanted to ask, if that's something to be concerned about. The parameters in script are just testing values, could that be it?

root@matej-Inspiron-15-7000:/diploma_thesis/odin_agent# python agent-click-file-gen.py 5 125 FF:FF:FF:FF:FF 127.0.0.1 6653 > agent.click
Traceback (most recent call last):
  File "agent-click-file-gen.py", line 3, in <module>
    aaa
NameError: name 'aaa' is not defined

**Comment by lalithsuresh** [comment]
The latest version of the code should not have this problem?

**Comment by uhlik1889** [comment]
When I deleted that "aaa" string, it works now. Could you fix that in the code, to prevent this happening in the future, to anyone else? Thanks

**Comment by lalithsuresh** [comment]
It's already fixed in the code!
